### ISSUE TITLE
For those of us who don't use foursquare

### ISSUE THREAD

**Issue by walwoodr** [learn-co-curriculum/web-auth-readme#11]
Having never used foursquare before this set of labs, my lack of friends made this last bit appear not to work. I'd suggest the below code snippet as a substitute for the views/searches/friends.html.erb code snippet.

```
<% if @friends.size > 0 %>
  <ul>
    <% @friends.each do |friend| %>
      <li><%= "#{friend['firstName']} #{friend['lastName']}" %></li>
    <% end %>
  </ul>
<% else %>
  <p>Looks like you don't have any foursquare friends yet.</p>
<% end %>
```

**Comment by gj** [comment]
Looks great @walwoodr !

If you make a PR, I'll happily merge it in!

**Comment by gj** [comment]
You're awesome — thanks! 🎉
