### ISSUE TITLE
"friend list" link is not found

### ISSUE THREAD

**Issue by IngridWong0715** [learn-co-curriculum/web-auth-readme#14]
The friend list link (https://developer.foursquare.com/docs/explore#req=users/self/friends)  returns a 404 not found

**Comment by ecssiah** [comment]
It looks like the API explore option is now under this route: `https://foursquare.com/developers/explore`.

The correct link for the example from the lab would be: `https://foursquare.com/developers/explore#req=users/self/friends`

**Comment by Peter-G-Stone** [comment]
hey just popping in to remind that this is still broken at the current moment

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
