### ISSUE TITLE
Changes to consider 

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/web-auth-readme#15]
1. This no longer seems to be true, in any case, in Seth's video, he can't find it, and tells students that it no longer exists. 

Top-tip: Like many API providers, Foursquare gives you a way to try API calls right from the documentation. Try it with the friends list to examine the response JSON.

2. It would be great to link to this video of the lesson: https://instruction.learn.co/student/video_lectures#/223
I asked the TC's and they found it for me. 

3. Also -- and this may be my lack of understanding: when the lesson forks, it comes with searches_controller#foursquare, but the lesson builds sessions_controller#create, which is pretty much the same thing. The first comes from the earlier lesson on API and Faraday. It's kind of confusing as to why both are there and whether they're needed, and they cause some bugs. 

4. Also, perhaps think about whether to include the solution/finished code in the repo, so it's clear what it looks like if a student gets lost or leaves out a step. 

Thanks, great lesson by the way, love this stuff!

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe some of your issues to have been resolved.
We'll take the other information into consideration in upcoming releases of this curriculum.
As always, thanks for contributing! 💙
