### ISSUE TITLE
Link to 'Friends List' Documentation is Expired

### ISSUE THREAD

**Issue by aburk3** [learn-co-curriculum/web-auth-readme#16]
<img width="870" alt="Screen Shot 2019-04-09 at 5 19 19 AM" src="https://user-images.githubusercontent.com/24820716/55792836-1cb1a600-5a87-11e9-8642-bb526edc2c85.png">
<img width="1163" alt="Screen Shot 2019-04-09 at 5 20 08 AM" src="https://user-images.githubusercontent.com/24820716/55792862-2935fe80-5a87-11e9-9436-466c1a3e3636.png">

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
