### ISSUE TITLE
Updating Gem File

### ISSUE THREAD

**Issue by YanezDiego** [learn-co-curriculum/web-auth-readme#17]
Gem file currently throws deprecation errors. 
the errors are as follow

`/Users/johnathonwood/.rvm/gems/ruby-2.6.1/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/Users/johnathonwood/.rvm/gems/ruby-2.6.1/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
Exiting
Traceback (most recent call last):
	8480: from bin/rails:3:in &#96;<main>'
	8479: from bin/rails:3:in &#96;load'
	8478: from /Users/johnathonwood/Development/code/web-auth-readme-online-web-pt-102218/bin/spring:13:in &#96;<top (required)>'
	8477: from /Users/johnathonwood/Development/code/web-auth-readme-online-web-pt-102218/bin/spring:13:in &#96;require'
	8476: from /Users/johnathonwood/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in &#96;<top (required)>'
	8475: from /Users/johnathonwood/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/binstub.rb:31:in &#96;load'
	8474: from /Users/johnathonwood/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/bin/spring:49:in &#96;<top (required)>'
	8473: from /Users/johnathonwood/.rvm/gems/ruby-2.6.1/gems/spring-2.0.2/lib/spring/client.rb:30:in &#96;run'
	 ... 8468 levels...
	   4: from /Users/johnathonwood/.rvm/gems/ruby-2.6.1/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:131:in &#96;block (2 levels) in <class:Numeric>'
	   3: from /Users/johnathonwood/.rvm/gems/ruby-2.6.1/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:131:in &#96;block (2 levels) in <class:Numeric>'
	   2: from /Users/johnathonwood/.rvm/gems/ruby-2.6.1/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:131:in &#96;block (2 levels) in <class:Numeric>'
	   1: from /Users/johnathonwood/.rvm/gems/ruby-2.6.1/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:131:in &#96;block (2 levels) in <class:Numeric>'
/Users/johnathonwood/.rvm/gems/ruby-2.6.1/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:131:in &#96;block (2 levels) in <class:Numeric>': stack level too deep (SystemStackError)`

to fix above change `rails`  gem version above 5.0 or leave it without a version to grab the most recent.

`rescue in spec': Specified 'sqlite3' for database adapter, but the gem is not loaded.`

to fix above add the version `~> 1.3.6` to the sqlite3 gem.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
